config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'fetch_task' => 'tasks#single_task', as: 'single_task'
  get 'fetch_do_it' => 'tasks#do_it_widget', as: 'do_it_widget'
  get 'finish_task' => 'tasks#finish_task', as: 'finish_task'

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  def progress_forward

  end

  def progress_back

  end

  def return_done_status
    case self.done
    when true
      return "done"
    when false
      return "not-done"
    end
  end

  def finish_unfinish
    case self.done
    when true
      self.unfinish
    when false
      self.finish
    end
    self.save
  end

  def finish
    self.done = true
  end

  def unfinish
    self.done = false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  def index
    @tasks = Task.all.reverse
  end

  def show
    @task = Task.find(params.fetch(:id))
    @tasks = Task.all.reverse
  end

  def new
    @task = Task.new
    respond_to do |format|
      format.js
    end
  end

  def create
    p post = params.fetch(:post)
    @task = Task.create(title: post.fetch(:title), task: post.fetch(:task))
    @tasks = Task.all.reverse
    p @task
  end

  def edit
    @task = Task.find(params.fetch(:id))
    respond_to do |format|
      format.js
    end
  end

  def update
    @task = Task.find(params.fetch(:id))
    p put = params.fetch(:put)
    @task.update_attribute(:title, put.fetch(:title))
    @task.update_attribute(:task, put.fetch(:task))
    @tasks = Task.all.reverse
    p @task
    respond_to do |format|
      format.js { render :template => 'tasks/edited_task.js.erb', :layout => false }
    end
  end

  def destroy
    @task = Task.find(params.fetch(:id).to_i)
    p @task
    @task.destroy
    @tasks = Task.all.reverse
    respond_to do |format|
      format.js { render :template => 'tasks/destroy.js.erb', :layout => false }
    end
  end

  def single_task
    @task = Task.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def finish_task
    p 'finished task mofos'
    @task = Task.find(params.fetch(:id))
    @task.finish_unfinish
    respond_to do |format|
      format.js { render :template => 'tasks/single_task.js.erb', :layout => false }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_all_tasks.html.erb
<h1>The deeds that need doing:</h1>
<% if !!tasks %>
  <% tasks.each do |task| %>
  <div class="task-<%= task.return_done_status %> tasks">
    <h3><%= task.title %></h3>
    <%= button_to 'DO IT', single_task_path(id: task.id), class: 'btn btn-primary', method: :get, remote: true %>
  </div>
  <% end %>
<% else tasks.nil? %>
  <h3>No Tasks Yet</h3>
  <p>But that will change.</p>
<% end %>

app/views/application/_created_task.html.erb
<h2><%= task.title %></h2>
<p><%= task.task %></p>
<p>Done? <%= task.done %></p>
<p>Progress: <%= task.progress %></p>
  <%= button_to 'Check Task', finish_task_path(id: task.id), class: 'btn btn-default pull-left', method: :get, remote: true %>
  <%= button_to 'Delete', task_path(id: task.id), class: 'btn btn-default pull-left', method: :delete, remote: true  %>
  <%= button_to 'Edit', edit_task_path(id: task.id), class: 'btn btn-default pull-left', method: :get, remote: true %>

app/views/application/_destroyed_task.html.erb
<h2>Task has been deleted</h2>
<p>It is dead now.</p>

app/views/application/_do_it_widget.html.erb
<h1>DO IT</h1>
<iframe width="720" height="315" src="https://www.youtube.com/embed/ZXsQAXx_ao0" frameborder="0" allowfullscreen></iframe>
<p>
  Do it. Just do it. Don't let your dreams be dreams. Yesterday you said tomorrow. So just do it. Make your dreams come true. Just do it. Some people dream of success. While you're gonna wake up and work hard at it. Nothing is impossible. You should get to the point.Where anyone else would quit. And you're not going to stop there. No, what are you waiting for?. Do it. Just do it. Yes you can. Just do it. If you're tired of starting over,
</p>

<h2>Stop giving up</h2>

app/views/application/_edit_task.html.erb
<h2>Edit Task</h2>
<%= form_for task, as: :put, remote: true do |f| %>
<div class="form-group">
  <label for="title">Title</label>
  <%= f.text_field :title, value: task.title %>
</div>
<div class="form-group">
  <label for="task">Task</label>
  <%= f.text_area :task, value: task.task %>
</div>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/application/_edited_task.html.erb
<h2>Edited</h2>
<h2><%= task.title %></h2>
<p><%= task.task %></p>
<p>Done? <%= task.done %></p>
<p>Progress: <%= task.progress %></p>
  <%= button_to 'Check Task', finish_task_path(id: task.id), class: 'btn btn-default pull-left', method: :get, remote: true %>
  <%= button_to 'Delete', task_path(id: task.id), class: 'btn btn-default pull-left', method: :delete, remote: true  %>
  <%= button_to 'Edit', edit_task_path(id: task.id), class: 'btn btn-default pull-left', method: :get, remote: true %>

app/views/application/_new_task.html.erb
<h2>New Task</h2>
<%= form_for @task, as: :post, remote: true do |f| %>
<div class="form-group">
  <label for="title">Title</label>
  <%= f.text_field :title %>
</div>
<div class="form-group">
  <label for="task">Task</label>
  <%= f.text_area :task %>
</div>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/application/_single_task.html.erb
<h2><%= task.title %></h2>
<p><%= task.task %></p>

<%= button_to 'Delete', task_path(id: task.id), class: 'btn btn-default pull-left', method: :delete, remote: true  %>
<%= button_to 'Edit', edit_task_path(id: task.id), class: 'btn btn-default pull-left', method: :get, remote: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamsNoLonger</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="container-fluid">
        <%= yield %>
      </div>
    </body>
  </html>

app/views/tasks/create.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'created_task', locals: {task: @task}) %>")
$('#all-tasks').html("<%= escape_javascript(render partial: 'all_tasks', locals: {tasks: @tasks}) %>")

app/views/tasks/destroy.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'destroyed_task') %>")
$('#all-tasks').html("<%= escape_javascript(render partial: 'all_tasks', locals: {tasks: @tasks}) %>")

app/views/tasks/do_it_widget.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'do_it_widget') %>")

app/views/tasks/edit.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'edit_task', locals: {task: @task}) %>")

app/views/tasks/edited_task.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'edited_task', locals: { task: @task } ) %>")
$('#all-tasks').html("<%= escape_javascript(render partial: 'all_tasks', locals: {tasks: @tasks}) %>")

app/views/tasks/index.html.erb
<div class='row'>
  <div class='col-md-5'>
    <div id="all-tasks">
      <%= render partial: "all_tasks", locals: {tasks: @tasks} %>
    </div>
  </div>
  <div class='col-md-5'>
    <div class='affix'>
      <div class="btn-group btn-group-justified">
      <%= button_to 'Motivate', do_it_widget_path, method: :get,class: 'btn btn-default pull-left', remote: true %>
      <%= button_to 'New Task', new_task_path, method: :get,class: 'btn btn-default pull-left', remote: true %>
      </div>
      <div id="single-task">
        <%= render partial: 'do_it_widget' %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'new_task') %>")

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.task %></p>

app/views/tasks/single_task.js.erb
$('#single-task').html("<%= escape_javascript(render partial: 'single_task', locals: { task: @task } ) %>")

app/views/welcome/index.html.erb
<h1>Hey there!</h1>